# Generated by Django 6.0.5 on 2026-05-27 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=30)),
                ('classe', models.CharField(max_length=10)),
                ('birth_date', models.DateField()),
                ('registration_number', models.CharField(max_length=20)),
                ('guardian_contact', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Aluno',
                'db_table': 'Aluno',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuário',
                'db_table': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='ReportsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('result', models.TextField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiinfo.alunomodel')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiinfo.usermodel')),
            ],
            options={
                'verbose_name': 'Relatório',
                'db_table': 'Relatorio',
            },
        ),
        migrations.AddField(
            model_name='alunomodel',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiinfo.usermodel'),
        ),
        migrations.CreateModel(
            name='AdaptationsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('justification', models.TextField()),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiinfo.alunomodel')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiinfo.usermodel')),
            ],
            options={
                'verbose_name': 'Adaptação',
                'db_table': 'Adaptacao',
            },
        ),
    ]
